force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Date_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed__c</fullName>
    <defaultValue>NOW() +30</defaultValue>
    <inlineHelpText>Date when Position is closing</inlineHelpText>
    <label>Date Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Date_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Opened__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <inlineHelpText>Date when recruitment is opening</inlineHelpText>
    <label>Date Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>Tells the position is opened for which department</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Shows the status of the position</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <inlineHelpText>Shows the sub-status of the positions</inlineHelpText>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionManager.cls
//class used for position sobject
public class PositionManager {
    public static Id AddPosition(String name, String jd){
        Position__c pos= new Position__c();
        pos.Name = name;
        pos.Job_Description__c=jd;
        
        insert pos;
        
        return pos.Id;
    }
    public static Id AddPosition(String name, String jd, String status, String subStatus){
        Position__c pos=new Position__c(status__c = status, sub_status__c = subStatus);
        pos.Name = name;
        pos.Job_Description__c=jd;
        insert pos;
        return pos.id;
    }
    
    public static Boolean changeStatus(Id recId, String status){
        Position__c pos=new Position__c(Id=recId);
        
        pos.Status__c = status;
        update pos;
        return true;
    }
    
    public static Boolean changeSubStatus(Id recId, String subStatus){
        Position__c pos=new Position__c(Id=recId);
        pos.Sub_Status__c =subStatus;
        update pos;
        
        return true;
    }
    public static boolean deletePositionById(Id recId){
        Position__c pos=new Position__c();
        pos.Id = recId;
        delete pos;
        return true;
    }
    
    public static Boolean undeleteById(Id recId){
        Position__c pos=new Position__c();
        pos.Id = recId;
        undelete pos;
        return true;
    }

    public static List<Position__c> getAllPositions(){
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c];
    } 

    public static List<Position__c> getPositionsByDepartment(String deptName){
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c
               where department__c =:deptName];
    }

    public static List<Position__c>getPositionsByStatus(String stat){
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c 
               where Status__c=:stat];
    }
    public static List<Position__c> getPositionsBystatusAndDepartment(String stat, String deptName){
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c 
               where Status__c=:stat AND department__c =:deptName];
    }

    public static List<Position__c> getPositionsByStatusAndSubstatus(String stat, String substat){
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c
               where Status__c=:stat AND Sub_status__c=:substat];
    }
    public static List<Position__c> getPositionsByStatusOpenAndClosingin7Days(){
        DateTime advance7days = DateTime.now()+7;
        return[Select name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c
               where Status__c in('New','Open') AND date_closed__c <= :advance7days];
    }


    public static List<Position__c> getClosedPositionsToday(){
        DateTime closedtoday = DateTime.now();
        return[Select  name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c 
               where Status__c = 'Closed' AND date_closed__c = :closedtoday];
    }


    public static List<Position__c> getDepartmentwiseClosePositions(){
        return[Select  name, date_opened__c, date_closed__c, Department__c, Status__c, Sub_status__c From Position__c
               where Status__c ='Closed' order by Department__c];
    }
    
     public List<Position__c> getPositionByPriority(String Priority){
        return[Select name, Priority__c From Position__c
               where Priority__c = :Priority];
    }
    
    public List<Position__c> getPositionByDepartmentPriority(String deptName, String Priority){
        return[Select name, Priority__c From Position__c
               where Priority__c = :Priority and Department__c = :deptName];
    }
}