force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate Name</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Applying_For__c.field-meta.xml
<CustomField>
    <fullName>Position_Applying_For__c</fullName>
    <label>Position Applying For</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Interview Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Interviewed</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Name - REV-{0000000}</displayFormat>
        <label>Review No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Interviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Interviewer Name</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Job_Application_No__c.field-meta.xml
<CustomField>
    <fullName>Job_Application_No__c</fullName>
    <label>Job Application No</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReviewManager.cls
public class ReviewManager {
	 public static Id AddReviewManager(String Iname, String jano){
        Review__c rev= new Review__c();
        
        rev.Interviewer_Name__c= Iname;
        rev.Job_Application_No__c = jano;
        
        insert rev;
        
        return rev.Id;
    }

    public static Boolean changeInterviewName(Id recId, String Iname){
        Review__c rev= new Review__c(Id=recId);
        
		rev.Interviewer_Name__c= Iname;
        update rev;
        return true;
    }
    
    public static boolean deleteReviewById(Id recId){
        Review__c rev= new Review__c();
        rev.Id = recId;
        delete rev;
        return true;
    }
    
    public static Boolean undeleteById(Id recId){
        Review__c rev= new Review__c();
        rev.Id = recId;
        undelete rev;
        return true;
    }
    
    public static List<Job_Application__c> getAllJobApplications(){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c];
    } 

    public static List<Job_Application__c> getJobApplicationsByCandidateName(String cname){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               where Candidate_Name__c = :cname];
    }

    public static List<Job_Application__c>getJobApplicationsByPositionApplyingFor(String pos){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               where Position_Applying_For__c = :pos];
    }
    public static List<Job_Application__c> getJobApplicationsByStatus(String status){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               where Status__c = :status];
    }
    
    public static List<Job_Application__c> getJobApplicationsByStatusAndPosition(String status, String pos){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               where Status__c = :status and Position_Applying_For__c = :pos];
    }
    
    //job applications offered 
    public static List<Job_Application__c> getJobApplicationsForOpenStatus(){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               where Status__c = 'Offered'];
    }
    
    //position wise job applications
    public static List<Job_Application__c> getJobApplicationsForPositionwise(){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               order by Position_Applying_For__c];
    }
    
    //statuswise job applications
    public static List<Job_Application__c> getJobApplicationsForStatuswise(){
        return[Select name, Candidate_Name__c, Position_Applying_For__c, Status__c From Job_Application__c
               order by Status__c];
    }
}