force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Linkedin_Url__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_Url__c</fullName>
    <label>Linkedin Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <externalId>true</externalId>
    <label>Personal Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/CandidateManager.cls
public class CandidateManager {
    public static Id AddCandidate(String name, String email){
        Candidate__c cand= new Candidate__c();
        cand.Name = name;
        cand.Personal_Email__c = email;
        
        insert cand;
        return cand.Id;
    }
     public static boolean ChangeMobile(Id recId, String mobile){
        Candidate__c cand=new Candidate__c(Id=recId);
        cand.Mobile__c = mobile;
        update cand;
        return true;
    }
    
    public static boolean deleteCandidateById(Id recId){
        Candidate__c cand=new Candidate__c();
        cand.Id = recId;
        delete cand;
        return true;
    }
    
    public static Boolean undeleteById(Id recId){
        Candidate__c cand=new Candidate__c();
        cand.Id = recId;
        undelete cand;
        return true;
    }
    
    public static List<Candidate__c> getAllCandidates(){
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c From Candidate__c];
    } 

    public static List<Candidate__c> getCandidatesByMobile(String mobile){
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c From Candidate__c
               where mobile__c = :mobile];
    }

    public static List<Candidate__c>getCandidatesByLinkedIn(String linkedInURL){
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c From Candidate__c
               where Linkedin_Url__c = :linkedInURL];
    }
    public static List<Candidate__c> getCandidatesByMobileAndEmail(String mobile, String email){
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c From Candidate__c
               where mobile__c = :mobile AND Personal_Email__c = :email];
    }

    public static List<Candidate__c> getCandidatesByMobileAndLinkedIn(String mobile, String linkedInURL){
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c From Candidate__c
               where mobile__c = :mobile AND Linkedin_Url__c = :linkedInURL];
    }
    
    //candidates above 25 
    public static List<Candidate__c> getCandidatesByAge(){
        Date age = Date.today() - 25;
        return[Select name, mobile__c, Linkedin_Url__c, Personal_Email__c,	Birth_Date__c From Candidate__c
               where 	Birth_Date__c <= :age];
    }
}